### ISSUE TITLE
Decide on some User Stories

### ISSUE THREAD

**Issue by JoshSE2019** [Intro-to-SE-Spring-2020/Group3Project#12]
Decide on some User Stories for the project.

**Comment by JoshSE2019** [comment]
A possible user story would be to delete a post.

**Comment by Sdam627** [comment]
A possible user story would be the ability to dislike a post.

**Comment by princeproject911** [comment]
A possible user story would be the ability to share a post.

**Comment by JoeCrawford99** [comment]
I think users would like to follow other users.

**Comment by JoshSE2019** [comment]
#13 Issue made for delete a post.
#11 Issue made for share a post.
#8  Issue made for following a user.
