### ISSUE TITLE
Basic Design

### ISSUE THREAD

**Issue by JoshSE2019** [Intro-to-SE-Spring-2020/Group3Project#4]
How we shall design/implement our site.

**Comment by princeproject911** [comment]
Until we learn flask, all we can really do is draw out a plan and figure out what we need

**Comment by JoshSE2019** [comment]
True, also I've been looking at github videos and I've found this one to be very helpful.
https://www.youtube.com/watch?v=SWYqp7iY_Tc

As for Flask, it seems to require more setup than expected so make sure everyone starts working on install and some instructional videos.
Heres a good one I found:  https://www.youtube.com/watch?v=MwZwr5Tvyxo

**Comment by JoshSE2019** [comment]
Project started using Flask , sql lite, and html.
