### ISSUE TITLE
User's Stories

### ISSUE THREAD

**Issue by JoshSE2019** [Intro-to-SE-Spring-2020/Group3Project#5]
Sprint 1 for the lab due week 5.

**Comment by JoeCrawford99** [comment]
User Story - account - I would like to have a personal account.

**Comment by princeproject911** [comment]
User Story - Post - I would like to post a tweet so that other users can see what I want to share.

**Comment by Sdam627** [comment]
User Story - Liking Tweets/Posts - As a user, I would like to be able to 'like' individual tweets.

**Comment by JoeCrawford99** [comment]
User Story - follow - I would like to have the option to follow other users.
