### ISSUE TITLE
User Story - Follow a user

### ISSUE THREAD

**Issue by JoeCrawford99** [Intro-to-SE-Spring-2020/Group3Project#8]
I would like to have the option to follow other users.

**Comment by JoshSE2019** [comment]
Post how you may start to implement this feature.

**Comment by JoshSE2019** [comment]
This core feature I think should be implemented by either having a follow button next to the like button or by clicking on a user and having the follow button there(currently no like button there). 

Steps:
- Where should the Follow button be
- Make it do something in the database as a test
- Make it store the user Id

After these steps have been completed we shall move on to how we want the site to display who we are following.

These steps should not be hard as we have already incorporated most in with the Like button.

**Comment by JoshSE2019** [comment]
Follow button decided on User Post page. 
Next step is to code how to link the href line to the database. Most likely by making a new table.

**Comment by JoshSE2019** [comment]
How is everyone's code going for this portion?

**Comment by JoshSE2019** [comment]
Still have not received any updates or emails from the rest of the team. What is the progress on this User Story?

**Comment by JoshSE2019** [comment]
Sprint 3 is due tomorrow and still no updates or communication from the rest of the team. 
What progress has the team made on this user story?

**Comment by JoshSE2019** [comment]
Ability to follow a user has been completed by storing the followed username in the database and then linking in the sidebar to see followed user posts.
